spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacations
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      fromat-sql: false
      ddl-auto: none
    open-session-in-view: false



